### ISSUE TITLE
lb-ng cannot find module 'loopback'

### ISSUE THREAD

**Issue by annamz** [strongloop/loopback-sdk-angular-cli#14] opened 2014-11-16 21:58 UTC
Hi, I'm going through the tutorial http://docs.strongloop.com/display/public/LB/Add+a+client+app, after completing all the previous loopback tutorials.

When I execute 'lb-ng ../server/server.js js/lb-services.js' I get an error: Cannot find module 'loopback'.

Help please?

**Comment by bajtos** [comment] 2015-02-11 23:47
As part of our issue triage process, we are closing items that have been inactive for an extended period of time. Feel free to reopen this issue if you can provide any new information to help us with resolving the issue.

**Comment by ssegeo** [comment] 2015-03-30 10:09
Hi @bajtos I suppose i could give some feed back as to what I am getting since I am in the same dilema.
Here is a copy of my log

```javascript
Loading LoopBack app "C:\\UwAmp\\www\\hello_world\\server\\server.js"

module.js:340
    throw err;
    ^
Error: Cannot find module 'loopback'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at assertLoopBackVersion (C:\Users\devUser\AppData\Roaming\npm\node_modules\strongloop\node_modules\loopback-sdk-angular-cli\bin\lb-ng:59:25)
    at Object.<anonymous> (C:\Users\devUser\AppData\Roaming\npm\node_modules\strongloop\node_modules\loopback-sdk-angular-cli\bin\lb-ng:25:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
```
when i run ```node ../server/server.js``` it actually fires up the server without any errors, an ```npm install``` throws nothing to screen, it just silently runs through with no output whatsoever. 

I'l be very glad if you could get me out of this fix cause its stalling my progress. thanks

**Comment by bajtos** [comment] 2015-03-30 10:13
@ssegeo I am happy to help, but I need steps how to reproduce the problem on my machine. Can you reproduce the issue using our sandbox app described in [Reporting issues](https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report)? What is the exact command-line you are running? What is your Node version?

**Comment by ssegeo** [comment] 2015-03-30 10:14
Thanks @bajtos let me get to that right away...

**Comment by ssegeo** [comment] 2015-03-30 10:19
@bajtos For the command I'am using 
```
cd client
md js
lb-ng ../server/server.js js/models.js
```
nodejs version is v0.10.28

**Comment by bajtos** [comment] 2015-03-30 12:29
I managed to reproduce the problem on my machine :+1:

**Comment by bajtos** [comment] 2015-03-30 12:35
> I managed to reproduce the problem on my machine 

I'm taking back this comment, I reproduced it only because I forgot to run `npm install`.

---

Here is what I did on my Windows 8.1 machine:

1. Install the latest CLI version:

  ```
$  npm install -g loopback-sdk-angular-cli
C:\Users\bajtos\AppData\Roaming\npm\lb-ng -> C:\Users\bajtos\AppData\Roaming\npm\node_modules\loopback-sdk-angular-cli\bin\lb-ng
C:\Users\bajtos\AppData\Roaming\npm\lb-ng-doc -> C:\Users\bajtos\AppData\Roaming\npm\node_modules\loopback-sdk-angular-cli\bin\lb-ng-doc
loopback-sdk-angular-cli@1.1.4 C:\Users\bajtos\AppData\Roaming\npm\node_modules\loopback-sdk-angular-cli
├── semver@2.3.2
├── optimist@0.6.1 (wordwrap@0.0.2, minimist@0.0.10)
├── loopback-sdk-angular@1.3.7 (ejs@1.0.0)
├── express@3.20.2 (basic-auth@1.0.0, merge-descriptors@1.0.0, methods@1.1.1, escape-html@1.0.1, cookie-signature@1.0.6, utils-merge@1.0.0, fresh@0.2.4, range-parser@1.0.2, cookie@0.1.2, vary@1.0.0, parseurl@1.3.0, content-type@1.0.1, content-disposition@0.5.0, commander@2.6.0, depd@1.0.0, debug@2.1.3, proxy-addr@1.0.7, etag@1.5.1,
 mkdirp@0.5.0, send@0.12.2, connect@2.29.1)
└── docular@0.6.6 (docular-doc-api-angular@0.0.3, q@1.2.0, colors@1.0.3, node.extend@1.1.3, q-fs@0.1.36, docular-doc-api-doc@0.0.8, fs-extra@0.17.0, request@2.54.0, q-io@1.9.4)
```

 2. Clone the sandbox repository

  ```
$ git clone https://github.com/strongloop/loopback-sandbox.git
$ cd loopback-sandbox
```

 3. Install modules

  ```
$ npm install
```

4. Run your command

  ```
$ cd client
$ md js
$ lb-ng ../server/server.js js/models.js
Loading LoopBack app "C:\\src\\loopback-sandbox\\server\\server.js"
Generating "lbServices" for the API endpoint "/api"
Warning: scope User.accessTokens targets class "AccessToken", which is not exposed
via remoting. The Angular code for this scope won't be generated.
Saving the generated services source to "C:\\src\\loopback-sandbox\\client\\js\\models.js"
```

Can you confirm that the steps above don't work on your machine?

Is there anything special about your environment?

**Comment by ssegeo** [comment] 2015-03-30 12:50
@bajtos thanks for timely reply, I doubt there is anything special with my environment, went through the procedures you've outlined, unfortunately it is still throwing the same error, I believe it is at my end so I've decided to reinstall the entire strongloop library, will get back to you.

**Comment by ssegeo** [comment] 2015-03-30 14:58
@bajtos I happen to have closed down on the cause of all my frustration and i believe it was an issue of symbolic links since my development is done from a shadow folder, sym linked to the dropbox folder, if that wasn't the cause of the issue then on could consinder the following remedy

```
#uninstall strongloop
npm uninstall -g strongloop

#update npm (@mine was 1.4.9)
npm install -g npm

#reinstall strongloop
npm install -g strongloop
```

I would appreciate if @annamz would give us some feedback on what the cause of the issue on his end that way perhaps we could get a clearer picture of the problem.

personally thats i how managed to overcome it.

@bajtos thanks for your time.

**Comment by bajtos** [comment] 2015-04-01 06:19
Thank you @ssegeo with sharing this information, I am glad you managed to solve the problem.

**Comment by bajtos** [comment] 2015-04-08 07:26
I am closing this issue as resolved then. @annamz feel free to reopen if the steps described in https://github.com/strongloop/loopback-sdk-angular-cli/issues/14#issuecomment-87713049 don't solve the problem for you AND you can provide more information to help us troubleshoot the problem.

**Closed by bajtos** 2015-04-08 07:26 UTC
Labels: triage, waiting

**Comment by gshireesh** [comment] 2016-02-29 17:56
i faced the same problem. but got it resolved using git bash than regular console.

**Comment by barocsi** [comment] 2016-07-27 13:40
It happens to me when running from other than c:\

**Comment by jjhesk** [comment] 2016-10-13 07:15
im using linux and it is now working. i used 
`md js` and  `cd client` and `lb-ng server/server.js` are command not found

**Comment by carlosalvarez91** [comment] 2016-11-27 12:12
similar error...

`Carloss-MBP:sample copy carlosalvarez$ lb-ng server/server.js client/www/lib/lb-services.js
Loading LoopBack app "/Users/carlosalvarez/Desktop/APIrest/Loopback/sample copy/server/server.js"
loopback deprecated loopback.compress is deprecated. Use `require('compression');` instead. server/server.js:11:17
module.js:590
    throw err;
    ^

SyntaxError: /Users/carlosalvarez/Desktop/APIrest/Loopback/sample copy/common/models/item.json: Unexpected end of JSON input
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:587:27)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at loadModelDefinition (/Users/carlosalvarez/Desktop/APIrest/Loopback/sample copy/node_modules/loopback-boot/lib/compiler.js:449:20)
    at /Users/carlosalvarez/Desktop/APIrest/Loopback/sample copy/node_modules/loopback-boot/lib/compiler.js:346:21
    at Array.forEach (native)
    at /Users/carlosalvarez/Desktop/APIrest/Loopback/sample copy/node_modules/loopback-boot/lib/compiler.js:344:8
    at Array.forEach (native)
`
I ve tried to uninstall globally strongloop, clear cache and install it again but nothing happens.
